// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Manga } from '../../../manga/content-types/manga/manga';
import { Manga_Plain } from '../../../manga/content-types/manga/manga';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface MangaChapter {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    chapter: number;
    chapterImages: { data: Media[] };
    manga?: { data: Manga };
    slug: string;
  };
}
export interface MangaChapter_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  chapter: number;
  chapterImages: Media[];
  manga?: Manga_Plain;
  slug: string;
}

export interface MangaChapter_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  chapter: number;
  chapterImages: number[];
  manga?: number;
  slug: string;
}

export interface MangaChapter_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  chapter: number;
  chapterImages: AdminPanelRelationPropertyModification<Media>[];
  manga?: AdminPanelRelationPropertyModification<Manga_Plain>;
  slug: string;
}
