// Interface automatically generated by schemas-to-ts

import { Manga } from '../../../manga/content-types/manga/manga';
import { Manga_Plain } from '../../../manga/content-types/manga/manga';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Genre {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    manga?: { data: Manga[] };
  };
}
export interface Genre_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  manga?: Manga_Plain[];
}

export interface Genre_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  manga?: number[];
}

export interface Genre_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  manga?: AdminPanelRelationPropertyModification<Manga_Plain>;
}
